# Generated by Django 2.1.7 on 2019-02-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title yet', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title yet', max_length=64)),
                ('questions', models.ManyToManyField(blank=True, related_name='posts', to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='VariantResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='no title yet', max_length=64)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='variant_result_pair',
            field=models.ManyToManyField(blank=True, related_name='posts', to='quiz.VariantResult'),
        ),
    ]
