# Generated by Django 2.1.7 on 2019-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(default='no name yet', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='no question yet', max_length=64)),
                ('answer', models.CharField(default='no question yet', max_length=64)),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name yet', max_length=64)),
                ('password', models.CharField(default='no password yet', max_length=64)),
                ('passed_quizes', models.ManyToManyField(blank=True, related_name='passed_quizes', to='quiz.PassedQuiz')),
            ],
        ),
        migrations.AddField(
            model_name='passedquiz',
            name='question_answer_result_pair',
            field=models.ManyToManyField(blank=True, related_name='question_answer_result', to='quiz.QuestionAnswerResult'),
        ),
    ]
