# Generated by Django 2.1.7 on 2019-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190303_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedquiz',
            name='quiz_name',
            field=models.CharField(default='no name yet, unique=True', max_length=64),
        ),
    ]
