# Generated by Django 2.1.7 on 2019-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190303_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedquiz',
            name='quiz_name',
            field=models.CharField(default='no name yet', max_length=64),
        ),
    ]
